
// Objective-C API for talking to the following Go packages
//
//	github.com/nathanborror/logger/pkg/logger
//
// File is generated by gomobile bind. Do not edit.
#ifndef __LoggerKit_FRAMEWORK_H__
#define __LoggerKit_FRAMEWORK_H__

#include "Logger.objc.h"
#include "Universe.objc.h"

#endif
