// Objective-C API for talking to github.com/nathanborror/logger/pkg/logger Go package.
//   gobind -lang=objc github.com/nathanborror/logger/pkg/logger
//
// File is generated by gobind. Do not edit.

#ifndef __Logger_H__
#define __Logger_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LoggerError;
@protocol LoggerMachine;
@class LoggerMachine;

@protocol LoggerMachine <NSObject>
- (NSData* _Nullable)current;
- (NSData* _Nullable)entryCreate:(NSString* _Nullable)text color:(int64_t)color;
- (NSData* _Nullable)entryDelete:(int64_t)id_;
- (NSData* _Nullable)entrySearch:(NSString* _Nullable)query;
- (NSData* _Nullable)entryUpdate:(int64_t)id_ text:(NSString* _Nullable)text color:(int64_t)color;
@end

/**
 * Error represents an error.
 */
@interface LoggerError : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull code;
@property (nonatomic) NSError* _Nullable err;
- (NSString* _Nonnull)error;
/**
 * MarshalJSON is a custom marshaller for the Error type.
 */
- (NSData* _Nullable)marshalJSON:(NSError* _Nullable* _Nullable)error;
- (BOOL)unwrap:(NSError* _Nullable* _Nullable)error;
@end

// skipped function ErrorProgrammerFailure with unsupported parameter or return types


/**
 * New sets up a new database if one doesn't already exist.
 */
FOUNDATION_EXPORT id<LoggerMachine> _Nullable LoggerNew(NSString* _Nullable name, NSError* _Nullable* _Nullable error);

// skipped function NewError with unsupported parameter or return types


@class LoggerMachine;

/**
 * Machine defines the state interface.
 */
@interface LoggerMachine : NSObject <goSeqRefInterface, LoggerMachine> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSData* _Nullable)current;
- (NSData* _Nullable)entryCreate:(NSString* _Nullable)text color:(int64_t)color;
- (NSData* _Nullable)entryDelete:(int64_t)id_;
- (NSData* _Nullable)entrySearch:(NSString* _Nullable)query;
- (NSData* _Nullable)entryUpdate:(int64_t)id_ text:(NSString* _Nullable)text color:(int64_t)color;
@end

#endif
